"""feat(db): create matchmaking tables

Revision ID: abdc8f800d92
Revises: 9419272e4c85
Create Date: 2025-09-29 22:08:13.717871

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "abdc8f800d92"
down_revision: str | Sequence[str] | None = "9419272e4c85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchmaking_pools",
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matchmaking_pools_active"), "matchmaking_pools", ["active"], unique=False)
    op.create_index(op.f("ix_matchmaking_pools_id"), "matchmaking_pools", ["id"], unique=False)
    op.create_index(op.f("ix_matchmaking_pools_ruleset_id"), "matchmaking_pools", ["ruleset_id"], unique=False)
    op.create_index(op.f("ix_matchmaking_pools_variant_id"), "matchmaking_pools", ["variant_id"], unique=False)
    op.create_table(
        "matchmaking_user_stats",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("first_placements", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("elo_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["lazer_users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "ruleset_id"),
    )
    op.create_table(
        "matchmaking_pool_beatmaps",
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("beatmap_id", sa.Integer(), nullable=False),
        sa.Column("mods", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["beatmap_id"], ["beatmaps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pool_id"], ["matchmaking_pools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pool_id", "beatmap_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matchmaking_pool_beatmaps")
    op.drop_table("matchmaking_user_stats")
    op.drop_index(op.f("ix_matchmaking_pools_variant_id"), table_name="matchmaking_pools")
    op.drop_index(op.f("ix_matchmaking_pools_ruleset_id"), table_name="matchmaking_pools")
    op.drop_index(op.f("ix_matchmaking_pools_id"), table_name="matchmaking_pools")
    op.drop_index(op.f("ix_matchmaking_pools_active"), table_name="matchmaking_pools")
    op.drop_table("matchmaking_pools")
    # ### end Alembic commands ###
