"""add table beatmap_tags

Revision ID: 4a827ddba235
Revises: 24a32515292d
Create Date: 2025-08-29 11:41:40.432684

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a827ddba235"
down_revision: str | Sequence[str] | None = "24a32515292d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lazer_user_achievements_achievement_id"), table_name="lazer_user_achievements")
    op.drop_index(op.f("uq_user_achievement"), table_name="lazer_user_achievements")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("uq_user_achievement"), "lazer_user_achievements", ["user_id", "achievement_id"], unique=True)
    op.create_index(
        op.f("ix_lazer_user_achievements_achievement_id"), "lazer_user_achievements", ["achievement_id"], unique=False
    )
    # ### end Alembic commands ###
