"""add beatmap ratings

Revision ID: 5e71de183b79
Revises: af88493881eb
Create Date: 2025-08-27 15:21:37.128768

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5e71de183b79"
down_revision: str | Sequence[str] | None = "af88493881eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beatmapsets", "ratings")
    op.add_column("daily_challenge_stats", sa.Column("last_update", sa.DateTime(), nullable=True))
    op.drop_index(op.f("uq_user_achievement"), table_name="lazer_user_achievements")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("uq_user_achievement"), "lazer_user_achievements", ["user_id", "achievement_id"], unique=True)
    op.drop_column("daily_challenge_stats", "last_update")
    op.add_column("beatmapsets", sa.Column("ratings", mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
