"""add beatmap_ratings table


Revision ID: dba1f8d9992e
Revises: 178873984b22
Create Date: 2025-08-26 13:08:59.433785

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dba1f8d9992e"
down_revision: str | Sequence[str] | None = "178873984b22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lazer_user_achievements_achievement_id"), table_name="lazer_user_achievements")
    op.drop_index(op.f("uq_user_achievement"), table_name="lazer_user_achievements")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("uq_user_achievement"), "lazer_user_achievements", ["user_id", "achievement_id"], unique=True)
    op.create_index(
        op.f("ix_lazer_user_achievements_achievement_id"), "lazer_user_achievements", ["achievement_id"], unique=False
    )
    # ### end Alembic commands ###
