import datetime
from pathlib import Path
import re
import subprocess
import sys

from datamodel_code_generator import DataModelType, generate

OUTPUT_FILE = Path("app/models/performance.py")


def generate_model(schema_file: Path):
    temp_file = OUTPUT_FILE.parent / "_temp.py"
    if temp_file.exists():
        temp_file.unlink()
    temp_file.touch()

    generate(
        input_=schema_file,
        output=temp_file,
        output_model_type=DataModelType.PydanticV2BaseModel,
        disable_future_imports=True,
        custom_file_header=(
            f"# Version: {datetime.datetime.now().strftime('%Y.%m.%d')}\n"
            "# Auto-generated by scripts/generate_ruleset_attributes.py.\n"
            "# Schema generated by https://github.com/GooGuTeam/custom-rulesets\n"
            "# Do not edit this file directly.\n"
            "# ruff: noqa: E501\n"
        ),
    )

    code = temp_file.read_text()
    output = code
    performance_attributes_classes = re.findall(r"class (\w+PerformanceAttributes)", code)
    performance_attributes_classes.append("PerformanceAttributes")
    output += "PerformanceAttributesUnion = " + " | ".join(performance_attributes_classes) + "\n"
    difficulty_attributes_classes = re.findall(r"class (\w+DifficultyAttributes)", code)
    difficulty_attributes_classes.append("DifficultyAttributes")
    output += "DifficultyAttributesUnion = " + " | ".join(difficulty_attributes_classes) + "\n"
    OUTPUT_FILE.write_text(output)
    temp_file.unlink(missing_ok=True)

    subprocess.Popen(  # noqa: S603
        ["uv", "run", "ruff", "check", "--fix", OUTPUT_FILE],  # noqa: S607
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    subprocess.Popen(  # noqa: S603
        ["uv", "run", "ruff", "format", OUTPUT_FILE],  # noqa: S607
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


if __name__ == "__main__":
    generate_model(Path(sys.argv[1]))
